books/__init__.py
from flask import Flask

def create_app():
	app = Flask(__name__, static_url_path='/static')

	#import books.views
	from books.views import books
	app.register_blueprint(books)
	
	return app

books/views.py
from flask import request, redirect, url_for, render_template, flash, session
from flask import current_app as app
from books import shelfAPI
from books import get_bookinfo
from flask import Blueprint
from werkzeug.exceptions import HTTPException
from books.yurindo import zaiko, zaiko_all

books = Blueprint('books', __name__)

@books.errorhandler(HTTPException)
def handle_exception(e):
    response = "エラー (error code:" + str(e.code) + ")"
    return render_template('books/result.html', result = response)

@books.route('/')
def show_top():
	return render_template('books/index.html')

@books.route('/tsundoku')
def input_userid():
    return render_template('books/tsundoku.html')

@books.route('/search', methods=['GET','POST'])
def search_tsundoku():
    error = None
    if request.method == 'POST':
        resultBooklog = shelfAPI.get_tsundoku(request.form['userid'], request.form['categoryid'])
        return render_template('books/result_list.html', result = resultBooklog)
    else:
        return "NOT POST METHOD"

@books.route('/amazon-info', methods=['GET','POST'])
def input_amazoninfo():
    return render_template('books/input_amazon_info.html')

@books.route('/amazon-info/info', methods=['POST'])
def get_amazon_info():
    error = None
    if request.method == 'POST':
        inputdata1 = request.form['amazon_info1']
        inputdata2 = request.form['amazon_info2']
        result = get_bookinfo.extract_amazoninfo(inputdata1, inputdata2)
    else:
        return "NOT POST METHOD"
    return render_template('books/result_amazon.html', result = result)

@books.route('/isbn', methods=['GET','POST'])
def input_isbn():
    return render_template('books/input_isbn.html')

@books.route('/quote', methods=['GET','POST'])
def get_quote():
    error = None
    if request.method == 'POST':
        resultGoogleAPI = get_bookinfo.book_quote(request.form['isbn'])
        return render_template('books/result_map.html', result = resultGoogleAPI)
    else:
        return "NOT POST METHOD"

@books.route('/yurindo', methods=['GET','POST'])
def yurindo():
    return render_template('books/input_yurindo.html')

@books.route('/zaiko', methods=['GET','POST'])
def zaiko_kensaku():
    error = None
    if request.method == 'POST':
        tenpo_list = ['0520','0510','0420']
        tenpo_name_list = ['アトレ大井町','グランデュオ蒲田','アトレ川崎']
        if request.form['tenpo'] != '':
            tenpo_list.append(request.form['tenpo'])
            tenpo_name_list.append("###")

        # 書籍情報を取得（Google Books API）
        resultGoogleAPI = get_bookinfo.book_quote(request.form['isbn'])
        # zaiko_list:在庫状況リスト, tana_list:棚番号リスト
        zaiko_list,tana_list = zaiko_all(request.form['isbn'], tenpo_list)
        return render_template('books/result_zaiko.html', tenpo_list = tenpo_list, tenpo_name_list = tenpo_name_list, zaiko_list = zaiko_list, tana_list = tana_list, result = resultGoogleAPI)
    else:
        return "NOT POST METHOD"

books/templates/books/index.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">メニュー<a>

<ul class="list-group">
  <a href="/tsundoku" class="list-group-item list-group-item-action">積読:  ブクログに登録した積読本を検索</a>
  <a href="/isbn" class="list-group-item list-group-item-action">書籍情報:   ISBNから書籍情報を検索</a>
  <a href="/amazon-info" class="list-group-item list-group-item-action">Kindle本情報: Kindle本の書籍情報をAmazonサイトから抽出</a>
  <a href="/yurindo" class="list-group-item list-group-item-action">在庫検索(有隣堂):   有隣堂の在庫状況を調べる</a>
</ul>
{% endblock %}

books/templates/books/input_amazon_info.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">Kindle本の情報をAmazonサイトから抽出</a>
<form action="{{ url_for('books.get_amazon_info') }}" method="post">
<img src="/static/amazon_sample_002.jpg" width="80%">
	<div class="form-group">
		<label for="amazoninfo1">①タイトル・著者</label>
        <textarea class="form-control" id="AmazonInfo1" rows="2"  name=amazon_info1></textarea>
		<label for="amazoninfo2">②出版社・発売日</label>
        <textarea class="form-control" id="AmazonInfo2" rows="8"  name=amazon_info2></textarea>
	</div>
	<button type="submit" class="btn btn-primary">抽出</button>
</form>
{% endblock %}

books/templates/books/input_isbn.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">ISBNから書籍情報を検索</a>
<form action="{{ url_for('books.get_quote') }}" method="post">
	<div class="form-group">
		<label for="ISBN">ISBN</label>
		<input type="text" class="form-control" id="ISBN" name=isbn>
	</div>
	<button type="submit" class="btn btn-primary">検索</button>
</form>
{% endblock %}

books/templates/books/input_yurindo.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">在庫検索（有隣堂）</a>
<form action="{{ url_for('books.zaiko_kensaku') }}" method="post">
	<div class="form-group">
		<label for="ISBN">ISBN</label>
		<input type="text" class="form-control" id="ISBN" name=isbn>
        対象店舗<br>
        ・大井町(0520), 蒲田(0510), 川崎(0420)<br>
		<label for="tenpo">・追加する場合：店舗ID(数字4桁)を入力</label>
		<input type="text" class="form-control" id="tenpo" name=tenpo>
	</div>
	<button type="submit" class="btn btn-primary">検索</button>
</form>
{% endblock %}

books/templates/books/result.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">検索結果</a>
	<div class="card">
		<div class="card-body">
			<p class="card-text">{{result}}</p>
		</div>
	</div>
	<div class="mt-3">
		<button type="button" class="btn btn-primary" onclick="history.back()">戻る</button>
	</div>
{% endblock %}

books/templates/books/result_amazon.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">検索結果</a>
	<div class="card">
        <div class="card-body">
            <h5 class="card-title">書籍情報</h5>
            <div class="row">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th scope="row">書名</th>
                                <td>{{result['title']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">著者</th>
                                <td>{{result['authorlist']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">出版年月日</th>
                                <td>{{result['publishedDate']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">出版社</th>
                                <td>{{result['publisher']}}</td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th scope="row">引用文</th>
                                <td>{{result['quote']}}</td>
                            </tr>
                        </tbody>
                    </table>
            </div>
        </div>
    </div>
	<div class="mt-3">
		<button type="button" class="btn btn-primary" onclick="history.back()">戻る</button>
	</div>
{% endblock %}

books/templates/books/result_list.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">検索結果: {{result[1]}}冊</a>
	<div class="card">
	    <ul>
                {% for i in result[0] %}
		    <li>{{i}}</li>
                {% endfor %}
            </ul>
	</div>
	<div class="mt-3">
		<button type="button" class="btn btn-primary" onclick="history.back()">戻る</button>
	</div>
{% endblock %}

books/templates/books/result_map.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">検索結果</a>
	<div class="card">
        <div class="card-body">
            <h5 class="card-title">書籍情報</h5>
            <div class="row">
                <div class="col-sm-3">
                    <img src={{result['thumbnail']}} alt="thumbnail" title="thumbnail">
                </div>
                <div class="col-sm-9">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th scope="row">書名</th>
                                <td>{{result['title']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">著者</th>
                                <td>{{result['authorlist']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">出版年月日</th>
                                <td>{{result['publishedDate']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">出版社</th>
                                <td>{{result['publisher']}}</td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th scope="row">引用文</th>
                                <td>{{result['quote']}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
	</div>
	<div class="mt-3">
		<button type="button" class="btn btn-primary" onclick="history.back()">戻る</button>
	</div>
{% endblock %}

books/templates/books/result_zaiko.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">検索結果</a>
	<div class="card">
        <div class="card-body">
            <h5 class="card-title">書籍情報</h5>
            <div class="row">
                <div class="col-sm-3">
                    <img src={{result['thumbnail']}} alt="thumbnail" title="thumbnail">
                </div>
                <div class="col-sm-9">
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th scope="row">書名</th>
                                <td>{{result['title']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">著者</th>
                                <td>{{result['authorlist']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">出版年月日</th>
                                <td>{{result['publishedDate']}}</td>
                            </tr>
                            <tr>
                                <th scope="row">出版社</th>
                                <td>{{result['publisher']}}</td>
                            </tr>
                        </tbody>
                    </table>
                    <table class="table table-bordered">
                        <tbody>
                            <tr>
                                <th scope="row">引用文</th>
                                <td>{{result['quote']}}</td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
	<div class="card">
        <div class="card-body">
            <h5 class="card-title">在庫状況</h5>
            <div class="table-responsive">
                <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col" class="text-nowrap">店舗名</th>
                        <th scope="col" class="text-nowrap">在庫状況</th>
                        <th scope="col" class="text-nowrap">棚番号</th>
                        <th scope="col" class="text-nowrap">店舗ID</th>
                    </tr>
                </thead>
                <tbody>
                    {% for i in range(tenpo_list | length) %}
                    <tr>
                        <td class="text-nowrap">{{ tenpo_name_list[i] }}</td>
                        <td class="text-nowrap">{{ zaiko_list[i] }}</td>
                        <td class="text-nowrap">{{ tana_list[i] }}</td>
                        <td class="text-nowrap">{{ tenpo_list[i] }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
                </table>
            </div>
        </div>
	</div>
	<div class="mt-3">
		<button type="button" class="btn btn-primary" onclick="history.back()">戻る</button>
	</div>
{% endblock %}

books/templates/books/tsundoku.html
{% extends "layout.html" %}
{% block body %}
<a class="navbar-brand">積読検索（Booklog）</a>
<form action="{{ url_for('books.search_tsundoku') }}" method="post">
	<div class="form-group">
		<label for="UserID">ユーザID</label>
		<input type="text" class="form-control" id="UserID" name=userid>
	</div>
	<div class="form-group">
		<label for="Category">カテゴリID (指定なしの場合：0）</label>
		<input type="text" class="form-control" id="Category" name=categoryid value='0'>
	</div>
	</div>
	<button type="submit" class="btn btn-primary">検索</button>
</form>
{% endblock %}

books/templates/layout.html
<!doctype html>
<title>書籍関連ツール</title>
<meta name="viewport" content="width=device-width,initial-scale=1">

<!-- CSS only -->
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

<!-- JS, Popper.js, and jQuery -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<!-- stylesheet -->
<link href="https://fonts.googleapis.com/earlyaccess/mplus1p.css" rel="stylesheet" type="text/css">
<link rel=stylesheet href="{{ url_for('static', filename='style.css') }}">

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('books.show_top') }}">書籍関連ツール</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controles="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="nav navbar-nav navbar-right">
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('books.input_userid') }}">積読</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('books.input_isbn') }}">書籍情報</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('books.input_amazoninfo') }}">Kindle本情報</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('books.yurindo') }}">在庫検索(有隣堂)</a>
                </li>
            </ul>
        </div>
    </nav>

	<div class="site-body">
        {% block body %}{% endblock %}
    </div>
</div>